In [1]:
import numpy as np

from sklearn.linear_model import LinearRegression

import sklearn.datasets as datasets

In [2]:
diabetes = datasets.load_diabetes()
diabetes

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990842, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06832974, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286377, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04687948,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452837, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00421986,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [3]:
X = diabetes['data']

y = diabetes['target']

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)

In [6]:
X_train.shape

(353, 10)

In [7]:
X_train[:5]

array([[-0.08906294, -0.04464164, -0.01159501, -0.03665645,  0.01219057,
         0.02499059, -0.03603757,  0.03430886,  0.02269202, -0.00936191],
       [ 0.02717829,  0.05068012, -0.00620595,  0.0287581 , -0.01670444,
        -0.00162703, -0.0581274 ,  0.03430886,  0.02930041,  0.03205916],
       [ 0.01628068,  0.05068012, -0.046085  ,  0.01154374, -0.03321588,
        -0.01603186, -0.01026611, -0.00259226, -0.0439854 , -0.04249877],
       [ 0.04170844,  0.05068012, -0.01590626,  0.01728186, -0.03734373,
        -0.01383982, -0.02499266, -0.01107952, -0.04687948,  0.01549073],
       [-0.02367725, -0.04464164, -0.01590626, -0.01255635,  0.02044629,
         0.04127431, -0.04340085,  0.03430886,  0.01407245, -0.00936191]])

In [10]:
# 该数据有正有负，说明此数据被处理过，归一化
X_train.std(axis = 0)

array([0.04734822, 0.0475412 , 0.04825435, 0.04607366, 0.04724651,
       0.04758674, 0.04927031, 0.04779197, 0.04657944, 0.04707625])

In [11]:
lr = LinearRegression()

In [12]:
lr.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [16]:
y_ = lr.predict(X_test)
y_.round(2)

array([ 85.12, 163.71,  63.55, 218.3 , 163.06, 150.55,  82.88, 193.32,
       208.76, 125.45, 107.27, 238.29,  59.74, 100.33, 112.66, 241.96,
       187.74, 188.74, 148.74, 199.43, 209.59, 229.64, 160.79, 149.22,
       135.61, 211.9 ,  65.1 , 130.51, 128.21, 127.21, 176.68, 198.78,
       217.68,  74.84, 122.66, 130.45,  99.47, 155.85,  71.78,  82.48,
       174.39,  90.78,  76.32, 159.8 , 230.54, 108.38, 209.47, 215.79,
       198.95,  71.31,  79.04,  90.62, 194.97, 191.12,  86.71, 238.62,
       162.68, 196.31, 210.25,  78.46, 147.33, 201.89, 291.03, 215.39,
       176.53,  58.49, 122.49, 192.83, 175.76, 130.75, 249.97, 152.78,
        79.42, 194.09, 224.39, 173.03, 213.03,  95.59, 216.38, 166.36,
        81.86,  93.82, 209.76, 116.94, 115.04, 144.28, 256.24, 179.02,
       169.27])

In [14]:
y_test

array([181., 179.,  77., 295., 131., 202.,  37., 257.,  52., 139., 102.,
       195.,  65.,  53.,  97., 306.,  78., 241.,  25., 186., 221., 261.,
       209., 100.,  40., 288.,  52.,  92., 145., 150.,  91., 265., 225.,
        77.,  84.,  53.,  54.,  85.,  55.,  80., 262.,  64., 200., 113.,
       232.,  97., 192., 275., 131.,  92., 138.,  49., 292., 232.,  55.,
       280., 220., 220., 265.,  89., 150., 268., 270., 152.,  77.,  85.,
       162., 123., 216., 131., 310., 246.,  42.,  68., 281., 141., 220.,
        72., 163., 178.,  51.,  71., 121.,  61., 160., 200., 336.,  52.,
       184.])

In [ ]:
'''The coefficient R^2 is defined as (1 - u/v), where u is the residual
sum of squares ((y_true - y_pred) ** 2).sum() and v is the total
sum of squares ((y_true - y_true.mean()) ** 2).sum().
The best possible score is 1.0 and it can be negative (because the
model can be arbitrarily worse). A constant model that always
predicts the expected value of y, disregarding the input features,
would get a R^2 score of 0.0.'''

In [15]:
# R2 决定系数
lr.score(X_test,y_test)

0.5100017419052714

In [17]:
# ((y_true - y_pred) ** 2).sum()
u = ((y_test - y_)**2).sum()
u

304838.15677376505

In [19]:
# ((y_true - y_true.mean()) ** 2).sum()
v = ((y_test - y_test.mean())**2).sum()
v

622120.8988764045

In [20]:
1 - u/v

0.5100017419052714

In [21]:
1 - np.var(y_test - y_)/np.var(y_test)

0.5108163438179167

In [22]:
np.abs(y_test - y_).mean()

47.55520213877001

In [25]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,mean_squared_log_error

In [24]:
mean_absolute_error(y_test,y_)

47.55520213877001