In [1]:
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import tensorflow as tf

d:\python3.6.8\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
d:\python3.6.8\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
d:\python3.6.8\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [3]:
data = np.array([[2,1,0,2,3],[9,5,4,2,0],[2,3,4,5,6],[1,2,3,1,0],[0,4,4,2,8]])
data

array([[2, 1, 0, 2, 3],
       [9, 5, 4, 2, 0],
       [2, 3, 4, 5, 6],
       [1, 2, 3, 1, 0],
       [0, 4, 4, 2, 8]])

In [4]:
filter_ = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
filter_

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [8]:
'''tf.nn.conv2d(
    input,
    filter,
    strides,
    padding,
    use_cudnn_on_gpu=True,
    data_format='NHWC',
    dilations=[1, 1, 1, 1],
    name=None,
)'''
# input Given an input tensor of shape `[batch, in_height, in_width, in_channels]`

input_data = tf.reshape(data,shape = [1,5,5,1])

input_data = tf.cast(input_data,dtype=tf.float32)

# and a filter / kernel tensor of shape

# `[filter_height, filter_width, in_channels, out_channels]`

filter_ = tf.cast(tf.reshape(filter_,shape = [3,3,1,1]),dtype=tf.float32)

# strides: A list of `ints`.
#     1-D tensor of length 4.

# adding: A `string` from: `"SAME", "VALID"`.
conv = tf.nn.conv2d(input= input_data,filter=filter_,strides=[1,1,1,1],padding='VALID')
conv

with tf.Session() as sess:
    ret = sess.run(conv)
    
    print(ret.reshape(3,3))

[[-5.  0.  1.]
 [-1. -2. -5.]
 [ 8. -1.  3.]]
