In [4]:
# PCA降维，通过矩阵运算

import numpy as np


In [1]:
import sklearn.datasets as datasets

In [2]:
from sklearn.decomposition import PCA

In [3]:
iris = datasets.load_iris()
X = iris['data']

y = iris['target']

In [4]:
X.shape

(150, 4)

In [6]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
s = StandardScaler()

In [17]:
pca = PCA(n_components=0.95,whiten=False)

X_pca = pca.fit_transform(X)
s.fit_transform(X_pca)

array([[-1.30971087,  0.65054141],
       [-1.32435711, -0.36051227],
       [-1.40967409, -0.29522986],
       [-1.33958163, -0.64830449],
       [-1.33146886,  0.66552653],
       [-1.11293846,  1.50992585],
       [-1.37627274, -0.18221302],
       [-1.28141939,  0.33277896],
       [-1.4084016 , -1.17789289],
       [-1.30416299, -0.23173293],
       [-1.22325714,  1.3138624 ],
       [-1.2748859 ,  0.03000162],
       [-1.35947347, -0.47887104],
       [-1.57304515, -1.04159745],
       [-1.29049784,  2.40088235],
       [-1.16426043,  2.72533645],
       [-1.28014238,  1.65117453],
       [-1.29222826,  0.6351676 ],
       [-1.07339558,  1.7777797 ],
       [-1.26280003,  1.04600854],
       [-1.12728243,  0.79708495],
       [-1.24119316,  0.88191703],
       [-1.56920777,  0.27184488],
       [-1.12361159,  0.20104806],
       [-1.14948296, -0.07593489],
       [-1.2231214 , -0.29740403],
       [-1.20465318,  0.26671917],
       [-1.25027614,  0.74896183],
       [-1.28795287,

In [13]:
# whiten = True就是对数据进行了归一化standard归一化
pca = PCA(n_components=0.95,whiten=True)

X_pca = pca.fit_transform(X)
X_pca

array([[-1.30533786,  0.64836932],
       [-1.31993521, -0.35930856],
       [-1.40496732, -0.29424412],
       [-1.33510889, -0.64613986],
       [-1.32702321,  0.6633044 ],
       [-1.10922246,  1.50488434],
       [-1.3716775 , -0.18160462],
       [-1.27714084,  0.33166784],
       [-1.40369908, -1.17396001],
       [-1.29980851, -0.23095919],
       [-1.2191728 ,  1.30947554],
       [-1.27062918,  0.02990145],
       [-1.35493432, -0.47727214],
       [-1.5677929 , -1.03811965],
       [-1.28618899,  2.39286603],
       [-1.16037307,  2.71623681],
       [-1.2758681 ,  1.64566141],
       [-1.28791362,  0.63304684],
       [-1.06981161,  1.77184386],
       [-1.25858365,  1.04251602],
       [-1.12351854,  0.79442356],
       [-1.23704894,  0.87897239],
       [-1.56396833,  0.27093722],
       [-1.11985996,  0.20037678],
       [-1.14564495, -0.07568135],
       [-1.21903752, -0.29641102],
       [-1.20063096,  0.26582861],
       [-1.24610158,  0.74646111],
       [-1.28365251,

In [ ]:
# 1、去中心化
# 2、协方差
# 3、特征值和特征向量计算
# 4、特征值选取百分比大于95%的特征所对应的特征向量
# 5、使用选取出来的特征向量和原数据进行矩阵运算

In [21]:
# 1、去中心化
A = X - X.mean(axis = 0)


In [22]:
import numpy as np

In [25]:
# 协方差
V = np.cov(A,rowvar=False)
V

array([[ 0.68569351, -0.042434  ,  1.27431544,  0.51627069],
       [-0.042434  ,  0.18997942, -0.32965638, -0.12163937],
       [ 1.27431544, -0.32965638,  3.11627785,  1.2956094 ],
       [ 0.51627069, -0.12163937,  1.2956094 ,  0.58100626]])

In [27]:
# 3、特征值和特征向量计算
T,TV = np.linalg.eig(V)
display(T,TV)

array([4.22824171, 0.24267075, 0.0782095 , 0.02383509])

array([[ 0.36138659, -0.65658877, -0.58202985,  0.31548719],
       [-0.08452251, -0.73016143,  0.59791083, -0.3197231 ],
       [ 0.85667061,  0.17337266,  0.07623608, -0.47983899],
       [ 0.3582892 ,  0.07548102,  0.54583143,  0.75365743]])

In [49]:
s.fit_transform(X.dot(np.linalg.eigh(V)[-1][:,[2,3]]))

array([[ 0.65054141,  1.30971087],
       [-0.36051227,  1.32435711],
       [-0.29522986,  1.40967409],
       [-0.64830449,  1.33958163],
       [ 0.66552653,  1.33146886],
       [ 1.50992585,  1.11293846],
       [-0.18221302,  1.37627274],
       [ 0.33277896,  1.28141939],
       [-1.17789289,  1.4084016 ],
       [-0.23173293,  1.30416299],
       [ 1.3138624 ,  1.22325714],
       [ 0.03000162,  1.2748859 ],
       [-0.47887104,  1.35947347],
       [-1.04159745,  1.57304515],
       [ 2.40088235,  1.29049784],
       [ 2.72533645,  1.16426043],
       [ 1.65117453,  1.28014238],
       [ 0.6351676 ,  1.29222826],
       [ 1.7777797 ,  1.07339558],
       [ 1.04600854,  1.26280003],
       [ 0.79708495,  1.12728243],
       [ 0.88191703,  1.24119316],
       [ 0.27184488,  1.56920777],
       [ 0.20104806,  1.12361159],
       [-0.07593489,  1.14948296],
       [-0.29740403,  1.2231214 ],
       [ 0.26671917,  1.20465318],
       [ 0.74896183,  1.25027614],
       [ 0.63555629,

In [ ]:
# 从数学上看，如果向量v与变换A满足Av=λv，则称向量v是变换A的一个特征向量，λ是相应的特征值。

In [40]:
V.dot(TV[:,0])

array([ 1.52802986, -0.35738162,  3.62221038,  1.51493333])

In [41]:
T[0]*TV[:,0]

array([ 1.52802986, -0.35738162,  3.62221038,  1.51493333])

In [32]:
a = np.arange(10)
a.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [33]:
T.cumsum()/T.sum()

array([0.92461872, 0.97768521, 0.99478782, 1.        ])

In [45]:
pca = PCA(n_components=0.97,whiten=True)

pca.fit_transform(X)

array([[-1.30533786,  0.64836932],
       [-1.31993521, -0.35930856],
       [-1.40496732, -0.29424412],
       [-1.33510889, -0.64613986],
       [-1.32702321,  0.6633044 ],
       [-1.10922246,  1.50488434],
       [-1.3716775 , -0.18160462],
       [-1.27714084,  0.33166784],
       [-1.40369908, -1.17396001],
       [-1.29980851, -0.23095919],
       [-1.2191728 ,  1.30947554],
       [-1.27062918,  0.02990145],
       [-1.35493432, -0.47727214],
       [-1.5677929 , -1.03811965],
       [-1.28618899,  2.39286603],
       [-1.16037307,  2.71623681],
       [-1.2758681 ,  1.64566141],
       [-1.28791362,  0.63304684],
       [-1.06981161,  1.77184386],
       [-1.25858365,  1.04251602],
       [-1.12351854,  0.79442356],
       [-1.23704894,  0.87897239],
       [-1.56396833,  0.27093722],
       [-1.11985996,  0.20037678],
       [-1.14564495, -0.07568135],
       [-1.21903752, -0.29641102],
       [-1.20063096,  0.26582861],
       [-1.24610158,  0.74646111],
       [-1.28365251,

In [43]:
# 前两个特征值，所对应的特征向量，分量97%
P = TV[:,[0,1]]

s.fit_transform(X.dot(P))

array([[-1.30971087, -0.65054141],
       [-1.32435711,  0.36051227],
       [-1.40967409,  0.29522986],
       [-1.33958163,  0.64830449],
       [-1.33146886, -0.66552653],
       [-1.11293846, -1.50992585],
       [-1.37627274,  0.18221302],
       [-1.28141939, -0.33277896],
       [-1.4084016 ,  1.17789289],
       [-1.30416299,  0.23173293],
       [-1.22325714, -1.3138624 ],
       [-1.2748859 , -0.03000162],
       [-1.35947347,  0.47887104],
       [-1.57304515,  1.04159745],
       [-1.29049784, -2.40088235],
       [-1.16426043, -2.72533645],
       [-1.28014238, -1.65117453],
       [-1.29222826, -0.6351676 ],
       [-1.07339558, -1.7777797 ],
       [-1.26280003, -1.04600854],
       [-1.12728243, -0.79708495],
       [-1.24119316, -0.88191703],
       [-1.56920777, -0.27184488],
       [-1.12361159, -0.20104806],
       [-1.14948296,  0.07593489],
       [-1.2231214 ,  0.29740403],
       [-1.20465318, -0.26671917],
       [-1.25027614, -0.74896183],
       [-1.28795287,