In [1]:
import numpy as np

from sklearn.linear_model import LinearRegression

import sklearn.datasets as datasets

D:\anacondna\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)


In [2]:
diabetes = datasets.load_diabetes()
diabetes

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990842, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06832974, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286377, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04687948,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452837, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00421986,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [3]:
X = diabetes['data']

y = diabetes['target']

In [4]:
from sklearn.model_selection import train_test_split

In [14]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)

In [15]:
X_train.shape

(353, 10)

In [16]:
X_train[:5]

array([[ 0.00538306, -0.04464164, -0.00297252,  0.04941532,  0.07410845,
         0.07071027,  0.04495846, -0.00259226, -0.00149859, -0.00936191],
       [-0.07090025, -0.04464164,  0.09295276,  0.01269137,  0.02044629,
         0.04252691,  0.00077881,  0.00035983, -0.05454415, -0.0010777 ],
       [ 0.0562386 , -0.04464164, -0.05794093, -0.00796586,  0.0520932 ,
         0.04910302,  0.05600338, -0.02141183, -0.02832024,  0.04448548],
       [-0.00188202, -0.04464164, -0.05147406, -0.02632783, -0.00844872,
        -0.01916334,  0.07441156, -0.03949338, -0.06832974, -0.09220405],
       [-0.0854304 ,  0.05068012, -0.02237314,  0.00121513, -0.03734373,
        -0.02636575,  0.01550536, -0.03949338, -0.07212845, -0.01764613]])

In [17]:
# 该数据有正有负，说明此数据被处理过，归一化
#std()   标准差
X_train.std(axis = 0)

array([0.04748723, 0.04766069, 0.04669176, 0.0454299 , 0.04837414,
       0.04872116, 0.04692438, 0.04802971, 0.04751205, 0.04787643])

In [18]:
lr = LinearRegression()

In [19]:
lr.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [20]:
lr.predict(X_test).round(2)

array([193.31, 126.14, 144.3 , 121.9 , 152.9 ,  71.09,  64.94, 180.56,
        94.64, 134.87, 144.75, 168.37,  71.93,  59.43, 197.58, 219.16,
        82.37, 180.64, 185.38, 180.08, 230.85, 166.69, 159.  , 220.14,
        85.58, 122.81,  91.46, 123.69, 102.24, 164.47,  77.9 , 234.42,
       207.32, 255.86, 123.8 , 175.05,  93.69, 128.17, 157.21, 156.43,
       239.33, 255.32, 159.51,  55.12, 151.46, 131.64, 139.57, 163.92,
       262.9 , 156.12,  79.26, 172.39,  94.33, 112.45,  73.4 , 160.55,
       165.79, 202.23,  70.62, 109.8 , 210.35,  87.6 , 124.7 , 204.38,
       221.91,  86.04,  56.41, 115.73, 123.84,  67.83, 191.48, 101.43,
       186.94, 230.22, 145.3 ,  62.31,  78.22, 166.53, 134.17,  99.55,
        70.85, 141.19,  49.49, 247.58, 171.28, 114.  , 190.27, 232.82,
       148.1 ])

In [21]:
y_test

array([241.,  97.,  25., 127.,  95., 134.,  43., 217., 137.,  49.,  88.,
       128., 104.,  99., 293., 173.,  60., 164., 163., 198., 280., 196.,
       113., 332.,  96., 178., 115., 113.,  94., 120.,  77., 270., 310.,
       242.,  51., 180.,  87., 135., 109., 100., 252., 245., 198.,  47.,
       246., 124., 219., 127., 346., 276.,  65., 147.,  54.,  72.,  55.,
       110., 109., 189.,  59., 109., 166.,  74.,  53., 265., 248.,  92.,
        63.,  79.,  71.,  52., 292.,  65.,  78., 195.,  97.,  96.,  77.,
       141., 103.,  31.,  72., 200.,  72., 281., 181., 199., 202., 258.,
       214.])

In [22]:
lr.score(X_test,y_test)

0.6097109594806098