In [1]:
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
y = np.array([1,3,5,7,9])

x = np.array([0,1,2,3,4])

plt.plot(x,y)
f = lambda x: 2*x + 1

# 实例

In [1]:
import sklearn.datasets as datasets

D:\anacondna\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)


In [2]:
data = datasets.load_boston()
data

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [3]:
X = data['data']
X.shape

(506, 13)

In [4]:
y = data['target']
y.shape

(506,)

In [5]:
data['feature_names']

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [6]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [8]:
# 回归问题------------->合适方程Xw = y
# 预测
# 真实情况下，数据和目标值之间一定存在一定关系，不一定是线性
# 处理问题，复杂问题，简单化，认为X和y之间的关系是线性
from sklearn.linear_model import LinearRegression

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.1)

In [11]:
lr = LinearRegression(fit_intercept=False)

lr.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=1, normalize=False)

In [13]:
lr.predict(X_test).round(2)

array([21.09, -7.46, 39.52, 44.86, 19.82, 25.22, 20.42, 21.12, 29.18,
       18.91, 26.67, 37.85, 13.4 , 18.2 , 15.96, 16.11, 16.05,  5.3 ,
       12.77, 21.48, 18.12, 16.79, 26.53, 32.04, 35.31, 21.07, 30.83,
       13.62, 41.03, 22.22,  7.75, 22.67, 20.12, 30.82, 17.27, 17.66,
       33.73, 18.4 , 28.19, 10.8 , 25.4 , 27.53, 23.19,  0.73, 24.51,
       19.36, 25.31, 13.31, 19.55, 22.8 , 24.51])

In [14]:
y_test

array([19.8,  7. , 48.3, 21.9, 17.1, 24.4, 22. , 19.9, 23. , 20.4, 17.8,
       50. , 13.9, 27.9, 20. ,  8.4, 16.2,  7.4, 19. , 21.4, 17.5, 22.5,
       23.7, 29. , 37.3, 21.1, 30.7, 21.9, 46. , 17.7, 14.4, 20.4, 19.9,
       23.6, 19.5, 19.6, 26.7, 17.8, 22. , 11.7, 23.8, 26.4, 21.4,  8.8,
       22.8,  7.2, 20.7, 15.7, 14.9, 20.6, 23.9])

In [15]:

w_ = lr.coef_
w_

array([-0.11504035,  0.04521628, -0.01989635,  3.7732892 , -2.91222729,
        6.04228501, -0.01216273, -1.05439371,  0.1927029 , -0.00873558,
       -0.39681765,  0.01535454, -0.44089308])

In [16]:
#截距
b_ = lr.intercept_
b_

0.0

In [18]:
# 这就是算法求解出来的方程
# f(X) = Xw_ + b_ 
# 预测X_test
X_test.dot(w_).round(2)

array([21.09, -7.46, 39.52, 44.86, 19.82, 25.22, 20.42, 21.12, 29.18,
       18.91, 26.67, 37.85, 13.4 , 18.2 , 15.96, 16.11, 16.05,  5.3 ,
       12.77, 21.48, 18.12, 16.79, 26.53, 32.04, 35.31, 21.07, 30.83,
       13.62, 41.03, 22.22,  7.75, 22.67, 20.12, 30.82, 17.27, 17.66,
       33.73, 18.4 , 28.19, 10.8 , 25.4 , 27.53, 23.19,  0.73, 24.51,
       19.36, 25.31, 13.31, 19.55, 22.8 , 24.51])